# Generated by Django 5.2.8 on 2025-11-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriasbrinquedos',
            name='imagem_categoria',
            field=models.ImageField(null=True, upload_to='categorias/'),
        ),
    ]
