# Generated by Django 5.2.8 on 2025-11-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriasbrinquedos_imagem_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brinquedos',
            options={'verbose_name': 'Brinquedo', 'verbose_name_plural': 'Brinquedos'},
        ),
        migrations.AlterModelOptions(
            name='estabelecimentos',
            options={'verbose_name': 'Estabelecimentos', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AddField(
            model_name='brinquedos',
            name='valor_brinquedo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
