# Generated by Django 5.2.8 on 2025-11-18 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_brinquedos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_site')),
            ],
            options={
                'verbose_name': 'Imagem do Site',
                'verbose_name_plural': 'Imagens do Site',
            },
        ),
        migrations.AlterField(
            model_name='imagemprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_projeto', to='core.projetos'),
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('brinquedos', models.ManyToManyField(related_name='eventos_brinquedos', to='core.brinquedos')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='ImagemEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='eventos/')),
                ('legenda', models.CharField(blank=True, max_length=255, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_evento', to='core.projetos')),
            ],
            options={
                'verbose_name': 'Imagem do Evento',
                'verbose_name_plural': 'Imagens dos Eventos',
            },
        ),
    ]
