# Generated by Django 5.2.8 on 2025-11-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_imagenssite_alter_imagemprojeto_projeto_eventos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedos',
            name='valor_brinquedo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
