# Generated by Django 5.2.8 on 2025-11-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_brinquedos_valor_brinquedo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedos',
            name='valor_brinquedo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
