# Generated by Django 5.2.8 on 2025-11-18 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_brinquedos_valor_brinquedo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemevento',
            name='projeto',
        ),
        migrations.AddField(
            model_name='imagemevento',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens_evento', to='core.eventos'),
        ),
    ]
