# Generated by Django 5.2.8 on 2025-11-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_imagemevento_projeto_imagemevento_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estabelecimentos',
            options={'verbose_name': 'Estabelecimentos', 'verbose_name_plural': 'Estabelecimentos'},
        ),
    ]
