# Generated by Django 5.2.8 on 2025-11-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_estabelecimentos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='brinquedos',
            name='altura_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura em cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='brinquedos',
            name='largura_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largura em cm', max_digits=6, null=True),
        ),
    ]
