# Generated by Django 5.2.8 on 2025-11-22 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_brinquedos_altura_cm_brinquedos_largura_cm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('codigo', models.CharField(max_length=12)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Cupom de Desconto',
                'verbose_name_plural': 'Cupons de Desconto',
            },
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='tagsbrinquedos',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='brinquedos',
            name='profundidade_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profundidade em cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='descricao_cliente',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimentos',
            name='brinquedos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimento', to='core.brinquedos'),
        ),
        migrations.CreateModel(
            name='Combos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('descricao', models.CharField(max_length=90)),
                ('valor_combo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brinquedos', models.ManyToManyField(related_name='combos', to='core.brinquedos')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
            },
        ),
        migrations.CreateModel(
            name='Promocoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('descricao', models.CharField(max_length=120)),
                ('brinquedos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='core.brinquedos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
