# Generated by Django 5.2.8 on 2025-11-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cupom_alter_clientes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedos',
            name='altura_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='brinquedos',
            name='largura_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='brinquedos',
            name='profundidade_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
