# Generated by Django 5.2.8 on 2025-11-22 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_clienteperfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrinquedosProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('nome_brinquedo_projeto', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=999)),
            ],
            options={
                'verbose_name': 'Brinquedo Projetado',
                'verbose_name_plural': 'Brinquedos Projetados',
            },
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='brinquedos',
        ),
        migrations.AddField(
            model_name='projetos',
            name='brinquedo_projetado',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='core.brinquedosprojeto'),
        ),
        migrations.CreateModel(
            name='ImagemProjetoBrinquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('imagem', models.ImageField(upload_to='projetos/')),
                ('legenda', models.CharField(blank=True, max_length=255, null=True)),
                ('brinquedo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_brinquedo_projeto', to='core.brinquedosprojeto')),
            ],
            options={
                'verbose_name': 'Imagem do Brinquedo Projetado',
                'verbose_name_plural': 'Imagens dos Brinquedos Projetados',
            },
        ),
        migrations.DeleteModel(
            name='ImagemProjeto',
        ),
    ]
