# Generated by Django 5.2.8 on 2025-11-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_brinquedosprojeto_remove_projetos_brinquedos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocoes',
            options={'verbose_name': 'Promoção', 'verbose_name_plural': 'Promoções'},
        ),
        migrations.AddField(
            model_name='promocoes',
            name='preco_promocao',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
