# Generated by Django 5.2.8 on 2025-11-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_promocoes_options_promocoes_preco_promocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='combos',
            name='imagem_combo',
            field=models.ImageField(null=True, upload_to='combos/'),
        ),
        migrations.AddField(
            model_name='promocoes',
            name='imagem_promocao',
            field=models.ImageField(null=True, upload_to='promocoes/'),
        ),
    ]
