# Generated by Django 5.2.8 on 2025-11-25 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_combos_imagem_combo_promocoes_imagem_promocao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='brinquedos',
            old_name='altura_cm',
            new_name='altura_m',
        ),
        migrations.RenameField(
            model_name='brinquedos',
            old_name='largura_cm',
            new_name='largura_m',
        ),
        migrations.RenameField(
            model_name='brinquedos',
            old_name='profundidade_cm',
            new_name='profundidade_m',
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('carrinho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='core.carrinho')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
