# Generated by Django 5.2.8 on 2025-11-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_carrinho_cupom_alter_carrinho_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasbrinquedos',
            name='imagem_categoria',
            field=models.ImageField(null=True, unique=True, upload_to='categorias/'),
        ),
    ]
