# Generated by Django 5.2.8 on 2025-12-17 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_categoriasbrinquedos_imagem_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriasbrinquedos',
            options={'verbose_name': 'Categoria de Produto', 'verbose_name_plural': 'Categorias de Produtos'},
        ),
    ]
