# Generated by Django 5.2.8 on 2025-12-29 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_categoriasbrinquedos_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimentos',
            name='brinquedos',
        ),
        migrations.AddField(
            model_name='brinquedos',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brinquedos', to='core.estabelecimentos'),
        ),
        migrations.CreateModel(
            name='BrinquedoSobMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profundidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brinquedo_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brinquedos')),
            ],
            options={
                'verbose_name': 'Brinquedo Sob Medida',
                'verbose_name_plural': 'Brinquedos Sob Medida',
            },
        ),
    ]
