# Generated by Django 5.2.8 on 2025-12-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_estabelecimentos_brinquedos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brinquedos',
            name='estabelecimento',
        ),
        migrations.AddField(
            model_name='brinquedos',
            name='estabelecimentos',
            field=models.ManyToManyField(blank=True, related_name='brinquedos', to='core.estabelecimentos'),
        ),
    ]
