# Generated by Django 5.2.8 on 2025-12-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_brinquedos_estabelecimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedos',
            name='imagem_brinquedo',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_brinquedos'),
        ),
    ]
