# Generated by Django 5.2.8 on 2026-01-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_brinquedos_imagem_brinquedo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimentos',
            name='imagem_estabelecimento',
            field=models.ImageField(blank=True, null=True, upload_to='estabelecimentos/'),
        ),
    ]
