# Generated by Django 5.2.8 on 2026-01-17 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_manutencao_manutencaoimagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='core.clienteperfil'),
        ),
    ]
