# Generated by Django 5.2.8 on 2026-01-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_manutencao_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='cep',
            field=models.CharField(help_text='Formato: 00000-000', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='endereco',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='numero',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='telefone_contato',
            field=models.CharField(help_text='Telefone para contato', max_length=20, null=True),
        ),
    ]
