# Generated by Django 5.2.8 on 2026-01-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_manutencao_bairro_manutencao_cep_manutencao_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='atualizada_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
