# Generated by Django 5.2.8 on 2026-01-19 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_manutencao_atualizada_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='usuario',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to='core.clienteperfil'),
        ),
    ]
