# Generated by Django 5.2.8 on 2026-01-19 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0028_remove_carrinho_usuario_carrinho_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='carrinho',
        ),
        migrations.AddField(
            model_name='venda',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('whatsapp', 'WhatsApp')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to='core.clienteperfil'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('aguardando_pagamento', 'Aguardando pagamento'), ('pago', 'Pago'), ('em_preparacao', 'Em preparação'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='criado', max_length=30)),
                ('total_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cupom_codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('cupom_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.clienteperfil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('nome_item', models.CharField(max_length=255)),
                ('tipo_item', models.CharField(choices=[('brinquedo', 'Brinquedo'), ('combo', 'Combo'), ('promocao', 'Promoção')], max_length=30)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedido')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='venda',
            name='pedido',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venda', to='core.pedido'),
        ),
    ]
