# Generated by Django 5.2.8 on 2026-01-20 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_venda_carrinho_venda_confirmado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to='core.clienteperfil'),
        ),
    ]
