# Generated by Django 5.2.8 on 2026-01-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_carrinho_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Em andamento'), ('C', 'Concluída'), ('X', 'cancelada')], default='P', max_length=1),
        ),
    ]
