# Generated by Django 5.2.8 on 2026-01-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('pix', 'PIX'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito')], max_length=20, null=True),
        ),
    ]
