# Generated by Django 5.2.8 on 2026-01-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_enderecoentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cpf',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
