# Generated by Django 5.2.8 on 2026-01-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_venda_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecoentrega',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone para contato na entrega', max_length=20, null=True),
        ),
    ]
