# Generated by Django 5.2.8 on 2026-01-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_enderecoentrega_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(default='Fabrica do Pery', max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
