# Generated by Django 5.2.8 on 2026-01-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_enderecoempresa_latitude_enderecoempresa_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecoentrega',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoentrega',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=50, null=True),
        ),
    ]
