# Generated by Django 5.2.8 on 2026-01-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_enderecoentrega_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecoempresa',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoempresa',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=50, null=True),
        ),
    ]
