# Generated by Django 5.2.8 on 2026-01-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_enderecoentrega_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('criado', 'Criado'), ('aguardando_pagamento', 'Aguardando pagamento'), ('pago', 'Pago'), ('em_preparacao', 'Em preparação'), ('saiu_entrega', 'Saiu para entrega'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='criado', max_length=30),
        ),
    ]
