# Generated by Django 5.2.8 on 2026-02-03 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_pedido_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrinquedoClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('quantidade_click', models.IntegerField(default=1)),
                ('brinquedo_clicado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks_brinquedo', to='core.brinquedos')),
            ],
            options={
                'verbose_name': 'Brinquedo Clicado',
                'verbose_name_plural': 'Brinquedos Clicados',
            },
        ),
        migrations.CreateModel(
            name='CategoriaClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('quantidade_click', models.IntegerField(default=1)),
                ('categoria_clicada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='core.categoriasbrinquedos')),
            ],
            options={
                'verbose_name': 'Categoria Clicada',
                'verbose_name_plural': 'Categorias Clicadas',
            },
        ),
        migrations.CreateModel(
            name='ComboClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('quantidade_click', models.IntegerField(default=1)),
                ('combo_clicado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks_combo', to='core.combos')),
            ],
            options={
                'verbose_name': 'Combo Clicado',
                'verbose_name_plural': 'Combo Clicados',
            },
        ),
        migrations.CreateModel(
            name='PromocaoClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('quantidade_click', models.IntegerField(default=1)),
                ('promocao_click', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks_promocao', to='core.promocoes')),
            ],
            options={
                'verbose_name': 'Promoção Clicada',
                'verbose_name_plural': 'Promoções Clicadas',
            },
        ),
    ]
