# Generated by Django 5.2.8 on 2026-02-04 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_brinquedoclick_categoriaclick_comboclick_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clienteperfil',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_perfil'),
        ),
    ]
