# Generated by Django 5.2.8 on 2026-02-10 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_clienteperfil_unique_user_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comboclick',
            options={'verbose_name': 'Combo Clicado', 'verbose_name_plural': 'Combos Clicados'},
        ),
        migrations.RemoveField(
            model_name='categoriaclick',
            name='categoria_clicada',
        ),
        migrations.RemoveField(
            model_name='promocaoclick',
            name='promocao_click',
        ),
        migrations.AddField(
            model_name='categoriaclick',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks_categoria', to='core.categoriasbrinquedos'),
        ),
        migrations.AddField(
            model_name='categoriaclick',
            name='nome_categoria',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='comboclick',
            name='descricao_combo',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='comboclick',
            name='valor_combo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promocaoclick',
            name='descricao_promocao',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='promocaoclick',
            name='preco_promocao',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promocaoclick',
            name='promocao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks_promocao', to='core.promocoes'),
        ),
        migrations.AlterField(
            model_name='comboclick',
            name='combo_clicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks_combo', to='core.combos'),
        ),
    ]
