# Generated by Django 5.2.8 on 2026-02-12 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_comboclick_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='brinquedo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupom', to='core.brinquedos'),
        ),
        migrations.AddField(
            model_name='cupom',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='core.categoriasbrinquedos'),
        ),
        migrations.AddField(
            model_name='cupom',
            name='cliente',
            field=models.ManyToManyField(null=True, related_name='cupons', to='core.clienteperfil'),
        ),
        migrations.AddField(
            model_name='cupom',
            name='quantidade_uso',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.CreateModel(
            name='ListaDesejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('brinquedos', models.ManyToManyField(related_name='lista_desejos', to='core.brinquedos')),
            ],
            options={
                'verbose_name': 'Lista de Desejo',
                'verbose_name_plural': 'Lista de Desejos',
            },
        ),
    ]
