# Generated by Django 5.2.8 on 2026-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_cupom_brinquedo_cupom_categoria_cupom_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='cliente',
            field=models.ManyToManyField(related_name='cupons', to='core.clienteperfil'),
        ),
    ]
