# Generated by Django 5.2.8 on 2026-02-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_cupom_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecasReposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('nome', models.CharField(max_length=120)),
                ('imagem_peca', models.ImageField(blank=True, null=True, upload_to='pecas_reposicao/')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=9)),
                ('preco_fornecedor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('descricao_peca', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Peça de Reposição',
                'verbose_name_plural': 'Peças de Reposição',
            },
        ),
    ]
