# Generated by Django 5.2.8 on 2026-02-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_pecasreposicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecasreposicao',
            name='descricao_peca',
            field=models.CharField(max_length=210),
        ),
    ]
