# Generated by Django 5.2.8 on 2026-02-24 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_pecasreposicao_descricao_peca'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('num_imagem', models.CharField(max_length=120)),
                ('peca_reposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem_peca_reposicao', to='core.pecasreposicao')),
            ],
            options={
                'verbose_name': 'Imagem de Peça de Reposição',
                'verbose_name_plural': 'Imagens de Peças de Reposição',
            },
        ),
    ]
