# Generated by Django 5.2.8 on 2026-02-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_imagempeca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pecasreposicao',
            name='imagem_peca',
        ),
    ]
