# Generated by Django 5.2.8 on 2026-02-24 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_pecasreposicao_imagem_peca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagempeca',
            options={'ordering': ['id'], 'verbose_name': 'Imagem de Peça de Reposição', 'verbose_name_plural': 'Imagens de Peças de Reposição'},
        ),
        migrations.RemoveField(
            model_name='imagempeca',
            name='num_imagem',
        ),
        migrations.AddField(
            model_name='imagempeca',
            name='imagem',
            field=models.ImageField(null=True, upload_to='pecas_reposicao/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='imagempeca',
            name='posicao',
            field=models.CharField(choices=[('frente', 'Frente'), ('lado_direito', 'Lado direito'), ('lado_esquerdo', 'Lado esquerdo'), ('tras', 'Traseira'), ('detalhe', 'Detalhe'), ('outro', 'Outro')], db_index=True, default='frente', max_length=20, verbose_name='Posição da imagem'),
        ),
        migrations.AlterField(
            model_name='imagempeca',
            name='peca_reposicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem_peca_reposicao', to='core.pecasreposicao', verbose_name='Peça'),
        ),
        migrations.AddIndex(
            model_name='imagempeca',
            index=models.Index(fields=['peca_reposicao'], name='core_imagem_peca_re_3bb4f0_idx'),
        ),
    ]
