# Generated by Django 5.2.8 on 2026-02-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_imagempeca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecasreposicao',
            name='ganho_potencial',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='pecasreposicao',
            name='preco_fornecedor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='pecasreposicao',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
