# Generated by Django 5.2.8 on 2026-02-24 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_pecasreposicao_ganho_potencial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('nome_categoria_peca', models.CharField(max_length=90)),
            ],
            options={
                'verbose_name': 'Categoria de Peça',
                'verbose_name_plural': 'Categorias de Peças',
            },
        ),
        migrations.AddField(
            model_name='pecasreposicao',
            name='categoria_peca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peca', to='core.categoriapeca'),
        ),
    ]
