# Generated by Django 5.2.8 on 2026-02-25 20:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_categoriapeca_pecasreposicao_categoria_peca'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteperfil',
            name='telefone',
            field=models.CharField(max_length=13, null=True, validators=[core.models.validar_telefone]),
        ),
    ]
