# Generated by Django 5.2.8 on 2026-02-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_clienteperfil_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecasreposicao',
            name='voltagem',
            field=models.CharField(blank=True, choices=[('5V', '5 Volts'), ('12v', '12 Volts'), ('sem_volts', 'Sem Voltagem')], max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(blank=True, choices=[('retirada', 'Retirada'), ('frete', 'Frete')], max_length=90, null=True),
        ),
    ]
