# Generated by Django 5.2.8 on 2026-02-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_clienteperfil_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_envio',
            field=models.CharField(choices=[('frete', 'Frete'), ('entrega', 'Entrega')], default='frete', max_length=30),
        ),
    ]
