# Generated by Django 5.2.8 on 2026-02-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_pedido_tipo_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecasreposicao',
            name='descricao_peca',
            field=models.CharField(max_length=250),
        ),
    ]
