# Generated by Django 5.2.8 on 2026-02-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_pecasreposicao_descricao_peca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pecasreposicao',
            name='categoria_peca',
        ),
        migrations.AddField(
            model_name='pecasreposicao',
            name='categoria_peca',
            field=models.ManyToManyField(blank=True, related_name='pecas', to='core.categoriapeca', verbose_name='Categorias'),
        ),
    ]
