# Generated by Django 5.2.8 on 2026-02-26 14:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_pecasreposicao_categoria_peca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteperfil',
            name='telefone',
            field=models.CharField(max_length=14, null=True, validators=[core.models.validar_telefone]),
        ),
    ]
