# Generated by Django 5.2.8 on 2026-02-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_clienteperfil_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecasreposicao',
            name='descricao_peca',
            field=models.CharField(max_length=999),
        ),
    ]
