# Generated by Django 5.2.8 on 2026-02-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_pecasreposicao_descricao_peca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aguardando_pagamento', 'Aguardando pagamento'), ('pago', 'Pago'), ('em_preparacao', 'Em preparação'), ('saiu_entrega', 'Saiu para entrega'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='criado', max_length=30),
        ),
    ]
