# Generated by Django 5.2.8 on 2026-03-03 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_carrinho_mp_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='carrinho_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_gerados', to='core.carrinho'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mp_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
