# Generated by Django 5.2.8 on 2026-02-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_pecasreposicao_voltagem_pedido_tipo_entrega'),
        ('core', '0067_carrinho_mp_payment_id'),
    ]

    operations = [
    ]
