# Generated by Django 5.2.8 on 2026-02-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_merge_20260227_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='external_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
