# Generated by Django 5.2.8 on 2026-03-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_pedido_carrinho_origem_alter_pedido_mp_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='tipo_envio',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='tipo_envio',
            field=models.CharField(choices=[('frete', 'Frete'), ('entrega', 'Entrega')], default='frete', max_length=30),
        ),
    ]
