# Generated by Django 5.2.8 on 2026-03-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_remove_pedido_tipo_envio_carrinho_tipo_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_envio',
            field=models.CharField(choices=[('frete', 'Frete'), ('entrega', 'Entrega')], default='frete', max_length=30),
        ),
    ]
