# Generated by Django 5.2.8 on 2026-02-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_pedido_external_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='tipo_item',
            field=models.CharField(choices=[('brinquedo', 'Brinquedo'), ('combo', 'Combo'), ('promocao', 'Promoção'), ('peca', 'Peça')], max_length=30),
        ),
    ]
