# Generated by Django 5.2.8 on 2026-03-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_pedido_tipo_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='mp_status',
        ),
    ]
