# Generated by Django 5.2.8 on 2026-03-01 19:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_itempedido_tipo_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinho',
            options={'verbose_name': 'Carrinho de Pedido', 'verbose_name_plural': 'Carrinhos de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='enderecoentrega',
            options={'verbose_name': 'Endereço de Entrega', 'verbose_name_plural': 'Endereços de Entregas'},
        ),
        migrations.AlterModelOptions(
            name='itemcarrinho',
            options={'verbose_name': 'Item de Carrinho', 'verbose_name_plural': 'Itens de Carrinho'},
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Itens de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='manutencao',
            options={'verbose_name': 'Manutenção', 'verbose_name_plural': 'Manutenções'},
        ),
        migrations.AlterModelOptions(
            name='manutencaoimagem',
            options={'verbose_name': 'Imagem de Manutenção', 'verbose_name_plural': 'Imagens de Manutenções'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cupom_codigo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cupom_percentual',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tipo_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tipo_envio',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='tipo_entrega',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='valor_entrega',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clienteperfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[core.models.validar_telefone]),
        ),
    ]
