# Generated by Django 5.2.8 on 2026-03-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_remove_pedido_mp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mp_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
