# Generated by Django 5.2.8 on 2026-03-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_carrinho_options_alter_enderecoentrega_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='mp_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
