# Generated by Django 5.2.8 on 2026-03-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_pedido_mp_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cpf_cliente',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
