# Generated by Django 5.2.8 on 2026-03-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_pedido_mp_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='tipo_envio',
        ),
    ]
