# Generated by Django 5.2.8 on 2026-03-02 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_pedido_cpf_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enderecoentrega',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido', to='core.enderecoentrega'),
        ),
    ]
