# Generated by Django 5.2.8 on 2026-03-04 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_remove_pedido_tipo_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasbrinquedos',
            name='nome_categoria',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Frete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fretes', to='core.clienteperfil')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
