# Generated by Django 5.2.8 on 2026-03-02 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_enderecoentrega_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='endereco_entrega',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='endereco_entrega',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrinho', to='core.enderecoentrega'),
        ),
    ]
