# Generated by Django 5.2.8 on 2026-03-04 16:33

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_categoriasbrinquedos_nome_categoria_frete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedos',
            name='imagem_brinquedo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='imagens_brinquedos'),
        ),
        migrations.AlterField(
            model_name='categoriasbrinquedos',
            name='imagem_categoria',
            field=models.ImageField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), unique=True, upload_to='categorias/'),
        ),
        migrations.AlterField(
            model_name='combos',
            name='imagem_combo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='combos/'),
        ),
        migrations.AlterField(
            model_name='estabelecimentos',
            name='imagem_estabelecimento',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='estabelecimentos/'),
        ),
        migrations.AlterField(
            model_name='imagemevento',
            name='imagem',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='eventos/'),
        ),
        migrations.AlterField(
            model_name='imagempeca',
            name='imagem',
            field=models.ImageField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='pecas_reposicao/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='promocoes',
            name='imagem_promocao',
            field=models.ImageField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='promocoes/'),
        ),
    ]
