# Generated by Django 5.2.8 on 2026-03-05 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_brinquedos_imagem_brinquedo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frete',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='frete',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='frete',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='frete',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='frete',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='frete',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='frete',
            name='criacao',
        ),
        migrations.RemoveField(
            model_name='frete',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='frete',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='frete',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='frete',
            name='usuario',
        ),
        migrations.AddField(
            model_name='frete',
            name='calculado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='frete',
            name='carrinho',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frete', to='core.carrinho'),
        ),
        migrations.AddField(
            model_name='frete',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='frete',
            name='tempo_estimado_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frete',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
