# Generated by Django 5.2.8 on 2026-03-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_remove_frete_ativo_remove_frete_atualizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frete',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='frete',
            name='atualizado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='frete',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
