# Generated by Django 5.2.8 on 2026-03-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_frete_ativo_frete_atualizado_frete_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='frete',
            name='bairro',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='frete',
            name='cidade',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='frete',
            name='estado',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='frete',
            name='numero',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='frete',
            name='rua',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
