# Generated by Django 5.2.8 on 2026-03-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_frete_bairro_frete_cidade_frete_estado_frete_numero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frete',
            options={'verbose_name': 'Frete', 'verbose_name_plural': 'Fretes'},
        ),
        migrations.RemoveField(
            model_name='frete',
            name='calculado_em',
        ),
    ]
