# Generated by Django 5.2.8 on 2026-03-06 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_frete_options_remove_frete_calculado_em'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frete',
            options={},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='distancia_km',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tempo_estimado_min',
        ),
        migrations.AddField(
            model_name='frete',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='impresso',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='tipo_envio',
            field=models.CharField(choices=[('frete', 'Frete'), ('retirada', 'Retirada')], default='frete', max_length=30),
        ),
        migrations.AlterField(
            model_name='frete',
            name='carrinho',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frete', to='core.carrinho'),
        ),
        migrations.AlterField(
            model_name='frete',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
