# Generated by Django 5.2.8 on 2026-03-06 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_frete_options_remove_pedido_distancia_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frete',
            name='carrinho',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frete', to='core.carrinho'),
        ),
    ]
