# Generated by Django 5.2.8 on 2026-03-06 13:32

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_frete_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemprojetobrinquedo',
            name='imagem',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='projetos/'),
        ),
    ]
