# Generated by Django 5.2.8 on 2026-03-10 12:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_imagemprojetobrinquedo_imagem'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clienteperfil',
            name='unique_user_perfil',
        ),
        migrations.AddField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cidade',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='rua',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='clienteperfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[core.models.validar_telefone]),
        ),
    ]
