# Generated by Django 5.2.8 on 2026-03-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_remove_clienteperfil_unique_user_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
