# Generated by Django 5.2.8 on 2026-03-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_carrinho_cpf_cnpj_pedido_total_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='total_final',
        ),
    ]
