# Generated by Django 5.2.8 on 2026-03-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_remove_pedido_total_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
