# Generated by Django 5.2.8 on 2026-03-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_pedido_total_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='mp_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
