# Generated by Django 5.2.8 on 2026-03-11 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_alter_pedido_mp_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='tipo_item',
            field=models.CharField(choices=[('brinquedo', 'Brinquedo'), ('combo', 'Combo'), ('promocao', 'Promoção'), ('pecas', 'Peças')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='core.clienteperfil'),
        ),
    ]
