# Generated by Django 5.2.8 on 2026-03-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_alter_itempedido_tipo_item_alter_pedido_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnderecoEntrega',
        ),
    ]
