# Generated by Django 5.2.8 on 2026-03-11 13:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_delete_enderecoentrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteperfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[core.models.validar_telefone]),
        ),
    ]
