# Generated by Django 5.2.8 on 2026-07-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_clienteperfil_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['pais', 'estado', 'cidade', 'descricao_cliente'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado',
            field=models.CharField(blank=True, help_text='Sigla da UF (ex: SP). Deixe em branco para clientes fora do Brasil.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='exibir_no_mapa',
            field=models.BooleanField(default=True, help_text='Desmarque para manter o cliente cadastrado sem exibi-lo no mapa público.'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ex: -23.550520. Clique com o botão direito no local no Google Maps para copiar.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ex: -46.633308. Clique com o botão direito no local no Google Maps para copiar.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='pais',
            field=models.CharField(default='Brasil', max_length=100),
        ),
        migrations.AddField(
            model_name='clientes',
            name='site_cliente',
            field=models.URLField(blank=True, help_text='Opcional: link do site/Instagram do cliente, exibido no popup do mapa.', null=True),
        ),
    ]
