# Generated by Django 5.2.8 on 2026-07-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_alter_clientes_options_clientes_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brinquedos',
            name='exibir_na_loja',
            field=models.BooleanField(default=False, help_text='Marque para este brinquedo aparecer também na Loja. Peças de reposição, promoções e combos entram na Loja automaticamente; brinquedos não -- só os marcados aqui.'),
        ),
    ]
