# Generated by Django 5.2.8 on 2026-07-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_brinquedos_exibir_na_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cep',
            field=models.CharField(blank=True, help_text='Só para clientes no Brasil. Preenchendo o CEP, cidade/estado e coordenadas são preenchidos automaticamente ao salvar (não precisa digitar latitude/longitude na mão).', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='rua',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(blank=True, help_text='Se não tiver CEP (ex: cliente fora do Brasil), preencha cidade/estado/país aqui -- as coordenadas também são calculadas automaticamente por eles.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Preenchido automaticamente a partir do CEP ou da cidade/país ao salvar. Só edite na mão se quiser corrigir uma localização específica.', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Preenchido automaticamente a partir do CEP ou da cidade/país ao salvar. Só edite na mão se quiser corrigir uma localização específica.', max_digits=9, null=True),
        ),
    ]
