# Generated by Django 5.2.8 on 2026-07-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_clientes_bairro_clientes_cep_clientes_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='site_cliente',
            field=models.URLField(blank=True, help_text='Link do Instagram do cliente. Aparece como "Visitar Instagram" no popup do mapa.', null=True),
        ),
    ]
