# Generated by Django 5.2.8 on 2026-07-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_alter_clientes_site_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='frete',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Geocodificado automaticamente a partir do CEP quando o frete é calculado.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='frete',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Geocodificado automaticamente a partir do CEP quando o frete é calculado.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tempo_estimado_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_envio',
            field=models.CharField(choices=[('frete', 'Frete'), ('retirada', 'Retirada')], default='frete', max_length=30),
        ),
    ]
