# Generated by Django 5.2.8 on 2026-07-29 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_frete_latitude_frete_longitude_pedido_distancia_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='brinquedo_descricao_livre',
            field=models.CharField(blank=True, default='', help_text='Identificação manual para equipamentos não catalogados, não registrados ou antigos.', max_length=180),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='brinquedo_nao_listado',
            field=models.BooleanField(default=False, help_text='Marque quando o equipamento não estiver no catálogo.'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='brinquedo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brinquedo_manutencoes', to='core.brinquedos'),
        ),
    ]
