# Generated by Django 5.2.8 on 2026-08-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0104_repara_colunas_cupom"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientes",
            name="precisao_local",
            field=models.CharField(
                blank=True,
                choices=[
                    ("exato", "Endereço exato"),
                    ("rua", "Meio da rua"),
                    ("bairro", "Centro do bairro"),
                    ("cidade", "Centro da cidade"),
                    ("manual", "Informada à mão"),
                ],
                default="",
                help_text="Até onde a busca automática conseguiu chegar. 'Centro da cidade' ou 'Centro do bairro' significa que o alfinete está na região, e não no endereço -- nesse caso vale abrir o Google Maps, copiar as coordenadas certas e colar acima.",
                max_length=10,
            ),
        ),
    ]
