# Generated by Django 5.2.8 on 2026-08-26 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0105_clientes_precisao_local"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("curtida", "Curtida"),
                            ("desejo", "Lista de desejos"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "dispositivo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Chave anônima do aparelho que registrou a interação.",
                        max_length=64,
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[("app", "Aplicativo"), ("site", "Site")],
                        db_index=True,
                        default="site",
                        max_length=6,
                    ),
                ),
                (
                    "brinquedo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoritos",
                        to="core.brinquedos",
                    ),
                ),
                (
                    "peca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoritos",
                        to="core.pecasreposicao",
                        verbose_name="Peça de reposição",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoritos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Curtida / desejo",
                "verbose_name_plural": "Curtidas e desejos",
                "ordering": ("-criacao", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("brinquedo__isnull", False), ("peca__isnull", True)
                            ),
                            models.Q(
                                ("brinquedo__isnull", True), ("peca__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="favorito_um_produto_apenas",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("brinquedo__isnull", False), ("usuario__isnull", False)
                        ),
                        fields=("tipo", "brinquedo", "usuario"),
                        name="favorito_brinquedo_por_conta",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("peca__isnull", False), ("usuario__isnull", False)
                        ),
                        fields=("tipo", "peca", "usuario"),
                        name="favorito_peca_por_conta",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("brinquedo__isnull", False), ("usuario__isnull", True)
                        ),
                        fields=("tipo", "brinquedo", "dispositivo"),
                        name="favorito_brinquedo_por_dispositivo",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("peca__isnull", False), ("usuario__isnull", True)
                        ),
                        fields=("tipo", "peca", "dispositivo"),
                        name="favorito_peca_por_dispositivo",
                    ),
                ],
            },
        ),
    ]
