# Generated by Django 5.2.8 on 2026-08-26 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0106_favorito"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecompensaCupom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                ("nome", models.CharField(max_length=90)),
                ("descricao", models.CharField(blank=True, max_length=180)),
                (
                    "custo_pontos",
                    models.PositiveIntegerField(
                        help_text="Quantos pontos o cliente gasta para resgatar."
                    ),
                ),
                (
                    "desconto_percentual",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Desconto do cupom gerado, em porcentagem.",
                        max_digits=5,
                    ),
                ),
                (
                    "validade_dias",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Dias de validade do cupom depois do resgate.",
                    ),
                ),
                (
                    "estoque",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantos ainda podem ser resgatados. Vazio = ilimitado.",
                        null=True,
                    ),
                ),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Posição na vitrine do aplicativo."
                    ),
                ),
            ],
            options={
                "verbose_name": "Recompensa da loja de pontos",
                "verbose_name_plural": "Recompensas da loja de pontos",
                "ordering": ("ordem", "custo_pontos", "id"),
            },
        ),
        migrations.CreateModel(
            name="CarteiraPontos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                ("saldo", models.IntegerField(default=0)),
                ("total_ganho", models.PositiveIntegerField(default=0)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carteira_pontos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carteira de pontos",
                "verbose_name_plural": "Carteiras de pontos",
            },
        ),
        migrations.CreateModel(
            name="ResgateCupom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                ("pontos_gastos", models.PositiveIntegerField()),
                ("expira_em", models.DateTimeField()),
                (
                    "cupom",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resgate",
                        to="core.cupom",
                    ),
                ),
                (
                    "recompensa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resgates",
                        to="core.recompensacupom",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resgates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resgate de cupom",
                "verbose_name_plural": "Resgates de cupons",
                "ordering": ("-criacao", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PontoGanho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("curtida", "Curtida no aplicativo"),
                            ("meta_desejo", "Meta da lista de desejos"),
                            ("meta_curtida", "Meta de curtidas"),
                            ("resgate", "Resgate de cupom"),
                            ("ajuste", "Ajuste manual"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                ("chave", models.CharField(max_length=60)),
                (
                    "pontos",
                    models.IntegerField(help_text="Negativo quando o cliente gasta."),
                ),
                ("descricao", models.CharField(blank=True, max_length=140)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pontos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ponto do cliente",
                "verbose_name_plural": "Pontos dos clientes",
                "ordering": ("-criacao", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "origem", "chave"), name="ponto_um_por_fato"
                    )
                ],
            },
        ),
    ]
