"""Só o rótulo do status cancelado, que estava em minúscula.

"cancelada" aparecia no meio de "Pendente", "Em andamento" e "Concluída",
na mesma coluna. É rótulo de exibição -- nenhum dado muda de valor.
"""

# Generated by Django 5.2.8 on 2026-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_cliente_unico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manutencao",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pendente"),
                    ("A", "Em andamento"),
                    ("C", "Concluída"),
                    ("X", "Cancelada"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
