# Generated by Django 5.2.8 on 2026-09-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0110_alter_manutencao_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="pecasreposicao",
            name="uso",
            field=models.CharField(
                choices=[
                    ("loja", "Peça da loja"),
                    ("manutencao", "Item de manutenção"),
                ],
                db_index=True,
                default="loja",
                help_text="Item de manutenção serve a orçamentos e O.S. e nunca entra na vitrine do site, mesmo estando ativo.",
                max_length=12,
                verbose_name="Onde esta peça é usada",
            ),
        ),
    ]
