// Executar com Node + jsdom instalado no ambiente de testes.
const fs = require('fs');
const path = require('path');
const assert = require('node:assert/strict');
const {JSDOM} = require('jsdom');
const root = path.resolve(__dirname, '..');
const base = fs.readFileSync(path.join(root, 'templates/base_inner.html'), 'utf8');
const painel = fs.readFileSync(path.join(root, 'static/interno/painel.js'), 'utf8');
const fragmento = base.slice(base.indexOf('<div class="ls-tema" id="lsAparencia">'), base.indexOf('<!-- ===================== central de avisos'));
const parcial = fs.readFileSync(path.join(root, 'templates/partials/material_foto.html'), 'utf8');
const dom = new JSDOM(`<html data-tema="lua"><body>${fragmento}<div class="modal"><form>${parcial}</form></div></body></html>`, {url:'https://interno.test/', runScripts:'outside-only', pretendToBeVisual:true});
const w = dom.window, d = w.document;
w.eval('var global = window; var Painel = window.Painel = {};');
w.eval(painel.slice(painel.indexOf('  Painel.aviso ='), painel.indexOf('  /* A espera de rede reescreve')));
w.eval(base.slice(base.indexOf('  var COR_DA_BARRA ='), base.indexOf('  const avisosBotao =')));
for (const tema of ['sol', 'lua', 'eclipse', 'sol']) {
  d.getElementById('lsAparenciaBotao').click();
  d.querySelector(`[data-tema-escolha="${tema}"]`).click();
  const aviso = d.querySelector('.ls-tarja-tema');
  assert.equal(aviso.dataset.temaAviso, tema);
  assert.equal(aviso.classList.contains('ok'), false);
  assert.equal(aviso.querySelectorAll('svg').length, 1);
  assert.equal(d.querySelectorAll('.ls-tarja-tema').length, 1);
  const ids = [...d.querySelectorAll('[id]')].map(el=>el.id);
  assert.equal(ids.length, new Set(ids).size);
  assert.equal(d.getElementById('lsAparenciaPainel').hidden, true);
}
w.eval(painel.slice(painel.indexOf('  Painel.fotoMaterial ='), painel.indexOf('  Painel.enviar =')));
let removidas = [];
w.URL.createObjectURL = ()=>'blob:foto-teste';
w.URL.revokeObjectURL = url=>removidas.push(url);
const form = d.querySelector('form');
const atualizar = w.Painel.fotoMaterial(form);
const campo = form.querySelector('[data-foto-input]');
const previa = form.querySelector('[data-foto-previa]');
atualizar('/foto-atual.webp');
assert.equal(previa.hidden, false);
Object.defineProperty(campo, 'files', {configurable:true, value:[new w.File(['teste'], 'foto.png', {type:'image/png'})]});
campo.dispatchEvent(new w.Event('change'));
assert.equal(previa.getAttribute('src'), 'blob:foto-teste');
const remover = form.querySelector('[data-foto-remover]');
remover.checked = true;
remover.dispatchEvent(new w.Event('change'));
assert.equal(previa.hidden, true);
assert.deepEqual(removidas, ['blob:foto-teste']);
remover.checked = false;
remover.dispatchEvent(new w.Event('change'));
assert.equal(previa.getAttribute('src'), '/foto-atual.webp');
Object.defineProperty(campo, 'files', {configurable:true, value:[new w.File(['svg'], 'invalido.svg', {type:'image/svg+xml'})]});
campo.dispatchEvent(new w.Event('change'));
assert.match(form.querySelector('[data-foto-erro]').textContent, /JPG/);
atualizar('');
assert.equal(previa.hidden, true);
assert.equal(previa.hasAttribute('src'), false);
dom.window.close();
console.log('OK: aviso com símbolo/cor por tema, sem duplicação; foto local, remoção, validação e liberação da prévia.');
