const fs = require('fs');
const path = require('path');
const assert = require('node:assert/strict');
const { JSDOM } = require('jsdom');
const js = fs.readFileSync(path.join(__dirname, '../static/interno/painel.js'), 'utf8');
const dom = new JSDOM('<nav class="ls-nav"><div class="ls-nav-section"><span class="ls-nav-caption">Estoque</span><a href="/stock/" class="active">Estoque</a></div><div class="ls-nav-section"><span class="ls-nav-caption">Comercial</span><a href="/clientes/">Clientes</a></div></nav>', {runScripts:'outside-only'});
dom.window.Painel = {};
dom.window.eval(js.slice(js.indexOf('  Painel.organizarSecoesMenu ='), js.indexOf('  Painel.montarTela =')));
dom.window.Painel.organizarSecoesMenu();
const d = dom.window.document;
const buttons = d.querySelectorAll('.ls-nav-section-toggle');
const groups = d.querySelectorAll('.ls-nav-links');
assert.equal(groups[0].hidden, false);
assert.equal(groups[1].hidden, true);
buttons[1].click();
assert.equal(groups[0].hidden, true);
assert.equal(groups[1].hidden, false);
assert.equal(buttons[1].getAttribute('aria-expanded'), 'true');
buttons[1].click();
assert.equal(groups[1].hidden, true);
dom.window.Painel.organizarSecoesMenu();
assert.equal(d.querySelectorAll('.ls-nav-section-toggle').length, 2);
assert.equal(d.querySelector('a[href="/clientes/"]').textContent, 'Clientes');
assert.equal(d.getElementById(buttons[0].getAttribute('aria-controls')), groups[0]);
dom.window.close();
console.log('OK: seção ativa, abrir/recolher, exclusividade, ARIA e inicialização sem duplicação.');
