const {JSDOM}=require('jsdom');
const fs=require('fs');
const assert=require('node:assert/strict');
const base='http://127.0.0.1:8765';
const root=require('node:path').resolve(__dirname,'../..');
(async()=>{
 const fixture=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
 const html=fixture['/orcamentos/'];
 const dom=new JSDOM(html,{url:base+'/orcamentos/',runScripts:'outside-only',pretendToBeVisual:true});
 const w=dom.window,d=w.document,requests=[];
 w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});
 w.scrollTo=()=>{}; w.HTMLElement.prototype.scrollIntoView=function(){};
 w.fetch=async (url,opt={})=>{
   const dest=new URL(url,w.location.href); requests.push([opt.method||'GET',dest.pathname+dest.search]);
   let payload, headers={'content-type':'application/json'};
   if(opt.method==='POST') {
     const action=opt.body.get('action');
     payload=action==='refazer'?fixture.refazer:action==='brinquedo_novo'?{status:'sucesso',brinquedo:{id:99,nome:'Novo brinquedo teste',valor:'90,00'}}:{status:'sucesso',msg:'Salvo'};
   } else if(dest.pathname==='/orcamentos/') {
     payload=fixture[dest.pathname+dest.search]||fixture['/orcamentos/'];
     headers={'content-type':'text/html'};
     if(opt.headers && opt.headers['X-LS-Fragmento']) headers['X-LS-Fragmento']='lista';
   } else payload={status:'sucesso',resultados:[],itens:[],avisos:[]};
   const response=new Response(typeof payload==='string'?payload:JSON.stringify(payload),{headers});
   Object.defineProperty(response,'url',{value:dest.href});return response;
 };
 w.LSTela={pronto:fn=>fn()};
 await new Promise(r=>d.readyState==='loading'?d.addEventListener('DOMContentLoaded',r,{once:true}):r());
 for(const f of ['vendor/bootstrap.bundle.min.js','ls-busca.js','painel.js','ls-filtro-local.js','ls-soft-navigation.js']) w.eval(fs.readFileSync(root+'/sistema_interno/static/interno/'+f,'utf8'));
 for(const script of d.querySelectorAll('#lsTelaScripts script:not([src])')) if(script.type!=='application/json') w.eval(script.textContent);
 const tick=async (f,msg)=>{for(let i=0;i<100;i++){if(f())return;await new Promise(r=>setTimeout(r,20));}throw Error(msg);};
 await tick(()=>d.querySelector('[data-editar]'),'editar presente');
 const id=d.querySelector('[data-editar]').dataset.editar;
 d.querySelector('[data-editar]').click();
 assert.equal(d.querySelector('#orcamentoId').value,id);
 w.Painel.fechar('modalOrcamento'); await new Promise(r=>setTimeout(r,550));
 await w.LSNavigation.go(base+'/orcamentos/?filtro=rascunhos');
 d.querySelector('[data-editar]').click();
 assert.equal(d.querySelector('#orcamentoId').value,id,'editar depois do filtro');
 d.querySelector('#addItem').click();assert.equal(d.querySelectorAll('#itensCorpo tr').length,2);
 d.querySelector('#itensCorpo tr:last-child .ls-item-descricao').value='Item adicional teste';
 d.querySelector('#itensCorpo tr:last-child .ls-item-valor').value='50,00';
 const mark=requests.length;
 d.querySelector('#formOrcamento').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 d.querySelector('#formOrcamento').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await tick(()=>!d.querySelector('#salvarOrcamento').disabled,'salvar liberado');
 assert.equal(requests.slice(mark).filter(x=>x[0]==='POST').length,1,'clique duplo envia uma vez');
 assert(!requests.slice(mark).some(x=>x[1].startsWith('/pronto/')),'POST sem preflight');
 await w.LSNavigation.go(base+'/orcamentos/?filtro=recusados');
 const ref=d.querySelector('[data-refazer]'); assert(ref,'proposta recusada disponível');
 ref.click();
 await tick(()=>d.querySelector('#orcamentoId').value!==id && d.querySelector('#modalOrcamento.show'),'refazer abre editor');
 assert(d.querySelectorAll('#itensCorpo tr').length>0,'itens copiados');
 assert.equal(d.querySelector('#itensCorpo .ls-item-valor').value,'100,00');
 assert(!d.querySelector('#addItem').disabled,'pode adicionar itens');
 const firstPrice=d.querySelector('#itensCorpo .ls-item-valor');
 firstPrice.value='75,00';
 d.querySelector('#novoBrinquedo').click();
 await tick(()=>d.querySelector('#modalBrinquedoNovo.show'),'cadastro filho abre');
 d.querySelector('#formBrinquedoNovo').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await tick(()=>d.querySelector('#modalOrcamento.show'),'volta ao orçamento');
 assert.equal(firstPrice.value,'75,00','preço digitado preservado');
 assert.equal(d.querySelectorAll('#itensCorpo tr').length,2,'novo item adicionado sem recarga');
 assert.equal(d.querySelector('#itensCorpo tr:last-child .ls-item-descricao').value,'Novo brinquedo teste');
 console.log(JSON.stringify({ok:true,requests,checks:['editar após filtro','adicionar item','salvar e reabilitar','POST único sem preflight','refazer abre itens editáveis','cadastro filho preserva preço e adiciona item']}));
 dom.window.close();
})().catch(e=>{console.error(e);process.exit(1)});
