# Generated by Django 5.2.8 on 2026-02-25 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('nome_jogo', models.CharField(max_length=200)),
                ('imagem_jogo', models.ImageField(upload_to='imagem_jogo/')),
                ('arquivo_jogo', models.FileField(upload_to='jogo/')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
        migrations.CreateModel(
            name='BuildJogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_build', models.CharField(max_length=200)),
                ('arquivo_build', models.FileField(upload_to='arquivo_build/')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_jogos.jogo')),
            ],
            options={
                'verbose_name': 'Build Jogo',
                'verbose_name_plural': 'Build Jogos',
            },
        ),
    ]
