# Generated by Django 5.2.8 on 2026-02-03 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_brinquedoclick_categoriaclick_comboclick_and_more'),
        ('sistema_interno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('nome_categoria', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Categoria de Despesa',
                'verbose_name_plural': 'Categorias de Despesas',
            },
        ),
        migrations.CreateModel(
            name='CentralItemPedido',
            fields=[
                ('itempedido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.itempedido')),
                ('descricao', models.CharField(max_length=90)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.itempedido',),
        ),
        migrations.CreateModel(
            name='CentralVendas',
            fields=[
                ('venda_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.venda')),
                ('descricao_venda', models.CharField(max_length=90)),
            ],
            options={
                'verbose_name': 'Central de Vendas',
            },
            bases=('core.venda',),
        ),
        migrations.CreateModel(
            name='EnderecoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('cep', models.CharField(max_length=18)),
                ('endereco', models.CharField(max_length=120)),
                ('numero', models.CharField(max_length=5)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
            ],
            options={
                'verbose_name': 'Endereço do Cliente',
                'verbose_name_plural': 'Endereços dos Clientes',
            },
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'materiais'},
        ),
        migrations.AddField(
            model_name='material',
            name='brinquedos_associados',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material', to='core.brinquedos'),
        ),
        migrations.AddField(
            model_name='material',
            name='descricao',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='CentralPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('descricao_pedido', models.CharField(max_length=90)),
                ('pedido', models.ForeignKey(max_length=90, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pedido')),
            ],
            options={
                'verbose_name': 'Central de Pedido',
                'verbose_name_plural': 'Central de Vendas',
            },
        ),
        migrations.CreateModel(
            name='ComprasMensais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('descricao_compra', models.CharField(max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compra', to='sistema_interno.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DespesasMensais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('descricao_despesa', models.CharField(max_length=90)),
                ('valor_despesa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria_despesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='sistema_interno.categoriadespesa')),
            ],
            options={
                'verbose_name': 'Despesa Mensal',
                'verbose_name_plural': 'Despesas Mensais',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('nome_cliente', models.CharField(max_length=90)),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=150)),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to='sistema_interno.enderecocliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='EstoqueMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('descricao_local', models.CharField(max_length=90)),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_fornecedor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='sistema_interno.material')),
            ],
            options={
                'verbose_name': 'Estoque de Material',
                'verbose_name_plural': 'Estoque de Materiais',
            },
        ),
        migrations.CreateModel(
            name='FinanceiroMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('descricao', models.CharField(max_length=90)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lucro', models.DecimalField(decimal_places=2, max_digits=6)),
                ('despesas_mensais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financeiro_mes', to='sistema_interno.despesasmensais')),
            ],
            options={
                'verbose_name': 'Financeiro Mensal',
                'verbose_name_plural': 'Financeiros Mensais',
            },
        ),
        migrations.CreateModel(
            name='ItensCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('materiais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_compra', to='sistema_interno.material')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
