# Generated by Django 5.2.8 on 2026-02-03 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_brinquedoclick_categoriaclick_comboclick_and_more'),
        ('sistema_interno', '0002_categoriadespesa_centralitempedido_centralvendas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='comprasmensais',
            name='material',
        ),
        migrations.RemoveField(
            model_name='itenscompra',
            name='materiais',
        ),
        migrations.AddField(
            model_name='enderecocliente',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='sistema_interno.cliente'),
        ),
        migrations.AddField(
            model_name='financeiromensal',
            name='mes',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='itenscompra',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sistema_interno.comprasmensais'),
        ),
        migrations.AddField(
            model_name='itenscompra',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_interno.material'),
        ),
        migrations.RemoveField(
            model_name='financeiromensal',
            name='despesas_mensais',
        ),
        migrations.AlterField(
            model_name='financeiromensal',
            name='lucro',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='material',
            name='brinquedos_associados',
        ),
        migrations.AlterUniqueTogether(
            name='estoquematerial',
            unique_together={('material', 'descricao_local')},
        ),
        migrations.AddField(
            model_name='financeiromensal',
            name='despesas_mensais',
            field=models.ManyToManyField(related_name='financeiros', to='sistema_interno.despesasmensais'),
        ),
        migrations.AddField(
            model_name='material',
            name='brinquedos_associados',
            field=models.ManyToManyField(related_name='materiais', to='core.brinquedos'),
        ),
    ]
