# Generated by Django 5.2.8 on 2026-02-12 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_cupom_cliente'),
        ('sistema_interno', '0004_remove_centralvendas_descricao_venda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralpedidos',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='centralpedidos',
            name='criacao',
        ),
        migrations.RemoveField(
            model_name='centralpedidos',
            name='id',
        ),
        migrations.RemoveField(
            model_name='centralpedidos',
            name='pedido',
        ),
        migrations.AddField(
            model_name='centralpedidos',
            name='pedido_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pedido'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CentralItemPedido',
        ),
    ]
