# Generated by Django 5.2.8 on 2026-02-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_interno', '0005_remove_centralpedidos_atualizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('nome_montador', models.CharField(max_length=90)),
            ],
            options={
                'verbose_name': 'Montadores',
                'verbose_name_plural': 'Montadores',
            },
        ),
        migrations.CreateModel(
            name='Setores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('nome_setor', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.AlterModelOptions(
            name='comprasmensais',
            options={'verbose_name': 'Compra Mensal', 'verbose_name_plural': 'Compras Mensais'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
