# Generated by Django 5.2.8 on 2026-02-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_interno', '0006_montadores_setores_alter_comprasmensais_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralpedidos',
            name='pedido_ptr',
        ),
        migrations.AddField(
            model_name='centralpedidos',
            name='atualizado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='centralpedidos',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='centralpedidos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='centralpedidos',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20),
        ),
    ]
