# Generated by Django 5.2.8 on 2026-08-21 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_imagembrinquedo_tipo"),
        ("sistema_interno", "0007_remove_centralpedidos_pedido_ptr_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                ("nome", models.CharField(max_length=120, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=150)),
                (
                    "cnpj",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="CNPJ / CPF"
                    ),
                ),
                ("site", models.CharField(blank=True, max_length=200)),
                ("observacoes", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "ordering": ("nome",),
            },
        ),
        migrations.AlterModelOptions(
            name="estoquematerial",
            options={
                "ordering": ("material__nome_material", "descricao_local"),
                "verbose_name": "Estoque de Material",
                "verbose_name_plural": "Estoque de Materiais",
            },
        ),
        migrations.AlterModelOptions(
            name="material",
            options={
                "ordering": ("nome_material",),
                "verbose_name": "Material",
                "verbose_name_plural": "materiais",
            },
        ),
        migrations.AddField(
            model_name="estoquematerial",
            name="comprado_em",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da compra"
            ),
        ),
        migrations.AddField(
            model_name="estoquematerial",
            name="estoque_minimo",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Abaixo disso o item entra na lista de reposição.",
                verbose_name="Quantidade mínima",
            ),
        ),
        migrations.AddField(
            model_name="estoquematerial",
            name="nota_fiscal",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="estoquematerial",
            name="observacoes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="material",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="material",
            name="codigo_interno",
            field=models.CharField(
                blank=True,
                help_text="Código usado na prateleira, na nota ou no catálogo do fornecedor.",
                max_length=30,
                verbose_name="Código interno",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="unidade",
            field=models.CharField(
                choices=[
                    ("un", "Unidade"),
                    ("pc", "Peça"),
                    ("m", "Metro"),
                    ("m2", "Metro quadrado"),
                    ("kg", "Quilo"),
                    ("l", "Litro"),
                    ("cx", "Caixa"),
                    ("rl", "Rolo"),
                    ("par", "Par"),
                ],
                default="un",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="comprasmensais",
            name="valor",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="despesasmensais",
            name="valor_despesa",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="estoquematerial",
            name="descricao_local",
            field=models.CharField(max_length=90, verbose_name="Local de guarda"),
        ),
        migrations.AlterField(
            model_name="estoquematerial",
            name="preco_fornecedor",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Valor pago por unidade"
            ),
        ),
        migrations.AlterField(
            model_name="financeiromensal",
            name="valor_bruto",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="financeiromensal",
            name="valor_liquido",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="itenscompra",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="material",
            name="brinquedos_associados",
            field=models.ManyToManyField(
                blank=True, related_name="materiais", to="core.brinquedos"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="descricao",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="tipo_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="material",
                to="sistema_interno.tipomaterial",
            ),
        ),
        migrations.AddField(
            model_name="estoquematerial",
            name="fornecedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estoques",
                to="sistema_interno.fornecedor",
            ),
        ),
        migrations.CreateModel(
            name="MovimentoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada (compra)"),
                            ("saida", "Saída (uso / montagem)"),
                            ("ajuste", "Ajuste de contagem"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("quantidade_resultante", models.IntegerField(default=0)),
                (
                    "valor_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor pago por unidade",
                    ),
                ),
                (
                    "documento",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Nota / pedido"
                    ),
                ),
                ("motivo", models.CharField(blank=True, max_length=150)),
                (
                    "ocorrido_em",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "estoque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentos",
                        to="sistema_interno.estoquematerial",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentos_estoque",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento de Estoque",
                "verbose_name_plural": "Movimentos de Estoque",
                "ordering": ("-ocorrido_em", "-id"),
            },
        ),
    ]
