# Generated by Django 5.2.8 on 2026-08-24 11:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_imagembrinquedo_tipo"),
        ("sistema_interno", "0008_fornecedor_alter_estoquematerial_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                ("nome_cliente", models.CharField(blank=True, max_length=120)),
                ("contato", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("enviado", "Enviado"),
                            ("aprovado", "Aprovado"),
                            ("recusado", "Recusado"),
                            ("expirado", "Expirado"),
                        ],
                        db_index=True,
                        default="rascunho",
                        max_length=12,
                    ),
                ),
                ("validade", models.DateField(blank=True, null=True)),
                (
                    "desconto",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "frete",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orcamentos",
                        to="sistema_interno.cliente",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orcamentos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Orçamento",
                "verbose_name_plural": "Orçamentos",
                "ordering": ("-criacao", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ProdutoInterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                ("nome", models.CharField(max_length=120)),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        help_text="Código usado na ordem de serviço e na etiqueta.",
                        max_length=30,
                        verbose_name="Código de produção",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("maquina", "Máquina"),
                            ("brinquedo", "Brinquedo"),
                            ("peca", "Peça / componente"),
                            ("outro", "Outro"),
                        ],
                        db_index=True,
                        default="maquina",
                        max_length=15,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "horas_producao",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=6,
                        verbose_name="Horas de montagem",
                    ),
                ),
                (
                    "preco_venda",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Preço de venda sugerido",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "brinquedo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Item correspondente no catálogo do site, quando houver.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produtos_internos",
                        to="core.brinquedos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto de produção",
                "verbose_name_plural": "Produtos de produção",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="OrdemProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejada", "Planejada"),
                            ("producao", "Em produção"),
                            ("concluida", "Concluída"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="planejada",
                        max_length=12,
                    ),
                ),
                ("prevista_para", models.DateField(blank=True, null=True)),
                ("concluida_em", models.DateTimeField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("baixa_aplicada", models.BooleanField(default=False)),
                (
                    "montador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordens",
                        to="sistema_interno.montadores",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordens_producao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "setor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordens",
                        to="sistema_interno.setores",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens",
                        to="sistema_interno.produtointerno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de produção",
                "verbose_name_plural": "Ordens de produção",
                "ordering": ("-criacao", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ItemOrcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                ("descricao", models.CharField(max_length=180)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="sistema_interno.orcamento",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itens_orcamento",
                        to="sistema_interno.produtointerno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do orçamento",
                "verbose_name_plural": "Itens do orçamento",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="ItemFichaTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.000"),
                        max_digits=10,
                        verbose_name="Quantidade por unidade",
                    ),
                ),
                ("observacao", models.CharField(blank=True, max_length=150)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fichas",
                        to="sistema_interno.material",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ficha",
                        to="sistema_interno.produtointerno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da ficha técnica",
                "verbose_name_plural": "Itens da ficha técnica",
                "ordering": ("material__nome_material",),
                "unique_together": {("produto", "material")},
            },
        ),
    ]
