# Generated by Django 5.2.8 on 2026-08-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema_interno", "0009_orcamento_produtointerno_ordemproducao_itemorcamento_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemproducao",
            name="colaborador",
            field=models.ForeignKey(
                blank=True,
                help_text="Funcionário que executará e atualizará as etapas.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="producoes_atribuidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ordemproducao",
            name="status",
            field=models.CharField(
                choices=[
                    ("planejada", "Planejada"),
                    ("producao", "Em produção"),
                    ("pausada", "Pausada"),
                    ("bloqueada", "Bloqueada"),
                    ("concluida", "Concluída"),
                    ("cancelada", "Cancelada"),
                ],
                db_index=True,
                default="planejada",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="GuiaEtapaProducao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                ("ordem", models.PositiveIntegerField(default=1)),
                ("titulo", models.CharField(max_length=120)),
                ("instrucoes", models.TextField(help_text="Explique, em detalhes, como executar esta etapa.")),
                ("criterio_conclusao", models.TextField(blank=True, verbose_name="Como conferir o resultado")),
                ("tempo_estimado_min", models.PositiveIntegerField(blank=True, null=True, verbose_name="Tempo estimado (minutos)")),
                ("ativo", models.BooleanField(default=True)),
                ("produto", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="guias_producao", to="sistema_interno.produtointerno")),
            ],
            options={
                "verbose_name": "Etapa do guia de produção",
                "verbose_name_plural": "Etapas dos guias de produção",
                "ordering": ("produto__nome", "ordem", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="guiaetapaproducao",
            constraint=models.UniqueConstraint(fields=("produto", "ordem"), name="guia_etapa_ordem_unica_por_produto"),
        ),
        migrations.CreateModel(
            name="ImagemGuiaProducao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                ("imagem", models.ImageField(upload_to="producao/guias/")),
                ("legenda", models.CharField(blank=True, max_length=160)),
                ("ordem", models.PositiveIntegerField(default=1)),
                ("etapa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="imagens", to="sistema_interno.guiaetapaproducao")),
            ],
            options={
                "verbose_name": "Imagem do guia de produção",
                "verbose_name_plural": "Imagens dos guias de produção",
                "ordering": ("ordem", "id"),
            },
        ),
        migrations.CreateModel(
            name="ExecucaoEtapaProducao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                ("status", models.CharField(choices=[("aguardando", "Aguardando"), ("andamento", "Em andamento"), ("pausada", "Pausada"), ("bloqueada", "Bloqueada / com dúvida"), ("concluida", "Concluída")], db_index=True, default="aguardando", max_length=12)),
                ("iniciado_em", models.DateTimeField(blank=True, null=True)),
                ("concluido_em", models.DateTimeField(blank=True, null=True)),
                ("observacao", models.TextField(blank=True)),
                ("atualizado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="etapas_producao_atualizadas", to=settings.AUTH_USER_MODEL)),
                ("guia_etapa", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="execucoes", to="sistema_interno.guiaetapaproducao")),
                ("ordem_producao", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="etapas_execucao", to="sistema_interno.ordemproducao")),
            ],
            options={
                "verbose_name": "Execução de etapa de produção",
                "verbose_name_plural": "Execuções de etapas de produção",
                "ordering": ("guia_etapa__ordem", "guia_etapa_id"),
            },
        ),
        migrations.AddConstraint(
            model_name="execucaoetapaproducao",
            constraint=models.UniqueConstraint(fields=("ordem_producao", "guia_etapa"), name="execucao_unica_por_ordem_e_etapa"),
        ),
        migrations.CreateModel(
            name="HistoricoProducao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                ("evento", models.CharField(choices=[("ordem_criada", "Ordem criada"), ("ordem_editada", "Ordem editada"), ("etapa", "Etapa atualizada"), ("cancelada", "Ordem cancelada")], max_length=20)),
                ("status_anterior", models.CharField(blank=True, max_length=20)),
                ("status_novo", models.CharField(blank=True, max_length=20)),
                ("observacao", models.TextField(blank=True)),
                ("etapa", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="historico", to="sistema_interno.execucaoetapaproducao")),
                ("ordem_producao", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="historico", to="sistema_interno.ordemproducao")),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="historico_producao", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Histórico de produção",
                "verbose_name_plural": "Históricos de produção",
                "ordering": ("-criacao", "-id"),
            },
        ),
    ]
