# Generated by Django 5.2.8 on 2026-08-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0106_favorito"),
        ("sistema_interno", "0012_orcamento_canais_envio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={
                "ordering": ("nome_cliente",),
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.AddField(
            model_name="cliente",
            name="documento",
            field=models.CharField(
                blank=True,
                help_text="Usado na nota e no contrato. Pode ficar em branco.",
                max_length=20,
                verbose_name="CPF ou CNPJ",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="estabelecimento",
            field=models.ForeignKey(
                blank=True,
                help_text="Liga este cadastro ao parceiro que aparece no site.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_internos",
                to="core.estabelecimentos",
                verbose_name="Parceiro publicado no site",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="observacoes",
            field=models.TextField(blank=True, verbose_name="Observações"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="parceiro",
            field=models.ForeignKey(
                blank=True,
                help_text="Buffet que atende este cliente, quando a festa vem por ele.",
                limit_choices_to={"tipo": "buffet"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_atendidos",
                to="sistema_interno.cliente",
                verbose_name="Buffet responsável",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("pessoa", "Pessoa física"),
                    ("empresa", "Empresa"),
                    ("buffet", "Buffet parceiro"),
                ],
                db_index=True,
                default="pessoa",
                max_length=10,
                verbose_name="Tipo de cadastro",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nome_cliente",
            field=models.CharField(max_length=90, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(
                blank=True, max_length=24, verbose_name="Telefone / WhatsApp"
            ),
        ),
    ]
