# Generated by Django 5.2.8 on 2026-08-26 12:12

import re

from django.db import migrations, models


def preencher_digitos(apps, schema_editor):
    """Cadastro que já existe também precisa ser achado pelo número."""
    Cliente = apps.get_model("sistema_interno", "Cliente")

    for cliente in Cliente.objects.exclude(telefone="").iterator():
        digitos = re.sub(r"\D", "", cliente.telefone or "")
        if digitos and digitos != cliente.telefone_digitos:
            cliente.telefone_digitos = digitos
            cliente.save(update_fields=["telefone_digitos"])



class Migration(migrations.Migration):

    dependencies = [
        ("sistema_interno", "0013_alter_cliente_options_cliente_documento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="telefone_digitos",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=20
            ),
        ),
        migrations.RunPython(
            preencher_digitos,
            migrations.RunPython.noop,
        ),
    ]
