# Generated by Django 5.2.8 on 2026-08-26 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema_interno", "0016_orcamento_formas_pagamento_envio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvioOrcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("link", "Link copiado"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "E-mail"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "destino",
                    models.CharField(
                        blank=True,
                        help_text="Telefone ou e-mail para onde a proposta foi mandada.",
                        max_length=254,
                    ),
                ),
                ("sucesso", models.BooleanField(default=True)),
                (
                    "detalhe",
                    models.CharField(
                        blank=True,
                        help_text="Motivo da falha, quando houve.",
                        max_length=240,
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios",
                        to="sistema_interno.orcamento",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="envios_orcamento",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Envio de orçamento",
                "verbose_name_plural": "Envios de orçamento",
                "ordering": ("-criacao", "-id"),
            },
        ),
    ]
