# Generated by Django 5.2.8 on 2026-08-27 14:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_interno', '0022_remove_cliente_mapa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='origem',
            field=models.CharField(choices=[('interno', 'Atendimento interno'), ('ambulante', 'Vendedor ambulante')], db_index=True, default='interno', help_text='Preenchida automaticamente pela função de quem criou a proposta.', max_length=20, verbose_name='Origem comercial'),
        ),
        migrations.AlterField(
            model_name='centralvendas',
            name='origem',
            field=models.CharField(choices=[('site', 'Site'), ('interno', 'Atendimento interno'), ('ambulante', 'Vendedor ambulante')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AvaliacaoBlocoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('bloco', models.CharField(choices=[('comercial', 'Comercial'), ('financeiro', 'Financeiro')], max_length=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('ajustes', 'Requer ajustes')], db_index=True, default='pendente', max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('avaliado_em', models.DateTimeField(blank=True, null=True)),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_blocos_orcamento', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_blocos', to='sistema_interno.orcamento')),
            ],
            options={
                'verbose_name': 'Avaliação de bloco do orçamento',
                'verbose_name_plural': 'Avaliações dos blocos dos orçamentos',
                'ordering': ('orcamento_id', 'bloco'),
                'constraints': [models.UniqueConstraint(fields=('orcamento', 'bloco'), name='uniq_avaliacao_bloco_orcamento')],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('setor', models.CharField(choices=[('producao', 'Produção'), ('criacao', 'Criação e site'), ('vendas', 'Vendas internas'), ('ambulante', 'Vendedores ambulantes'), ('financeiro', 'Financeiro'), ('gestao', 'Gestão')], db_index=True, max_length=16)),
                ('periodo', models.DateField(db_index=True, help_text='Primeiro dia do mês avaliado.')),
                ('nota', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('observacao', models.TextField(blank=True)),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_setores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação de setor',
                'verbose_name_plural': 'Avaliações dos setores',
                'ordering': ('-periodo', 'setor'),
                'constraints': [models.UniqueConstraint(fields=('setor', 'periodo'), name='uniq_avaliacao_setor_periodo')],
            },
        ),
    ]
