# Generated by Django 5.2.8 on 2026-08-27 18:57

import django.db.models.deletion
import sistema_interno.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_alter_manutencao_status'),
        ('sistema_interno', '0025_inscricaopush'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='motivo_negociacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='observacao_pagamento',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='orcamento_anterior',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_refeito', to='sistema_interno.orcamento'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pago_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pagamento pendente'), ('parcial', 'Pagamento parcial'), ('pago', 'Pago'), ('estornado', 'Estornado')], db_index=True, default='pendente', max_length=12),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='versao',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_resposta', 'Aguardando resposta'), ('em_negociacao', 'Em negociação'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('expirado', 'Expirado'), ('substituido', 'Substituído por nova versão')], db_index=True, default='rascunho', max_length=24),
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('nome_cliente', models.CharField(blank=True, max_length=120)),
                ('contato', models.CharField(blank=True, max_length=120)),
                ('whatsapp_cliente', models.CharField(blank=True, max_length=24)),
                ('email_cliente', models.EmailField(blank=True, max_length=254)),
                ('endereco_servico', models.CharField(blank=True, max_length=320)),
                ('tipo', models.CharField(choices=[('manutencao', 'Manutenção'), ('instalacao', 'Instalação'), ('revisao', 'Revisão preventiva'), ('visita', 'Visita técnica'), ('outro', 'Outro serviço')], db_index=True, default='manutencao', max_length=16)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aberta', 'Aberta'), ('agendada', 'Agendada'), ('em_execucao', 'Em execução'), ('aguardando_peca', 'Aguardando peça'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], db_index=True, default='rascunho', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], db_index=True, default='normal', max_length=10)),
                ('equipamento', models.CharField(max_length=180)),
                ('numero_serie', models.CharField(blank=True, max_length=80)),
                ('defeito_relatado', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('servico_executado', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=120)),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pagamento pendente'), ('parcial', 'Pagamento parcial'), ('pago', 'Pago'), ('estornado', 'Estornado')], db_index=True, default='pendente', max_length=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('observacao_pagamento', models.CharField(blank=True, max_length=240)),
                ('agendada_para', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('garantia_ate', models.DateField(blank=True, null=True)),
                ('token', models.CharField(db_index=True, default=sistema_interno.models.gerar_token_orcamento, editable=False, max_length=64, unique=True)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('cliente_ciente_em', models.DateTimeField(blank=True, null=True)),
                ('cliente_ciente_por', models.CharField(blank=True, max_length=120)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='sistema_interno.cliente')),
                ('manutencao', models.ForeignKey(blank=True, help_text='Chamado que originou a O.S., quando houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='core.manutencao')),
                ('orcamento', models.OneToOneField(blank=True, help_text='Referência histórica da proposta que originou a execução. Situação, valores recebidos e envios não são sincronizados.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordem_servico', to='sistema_interno.orcamento')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_criadas', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordem de serviço',
                'verbose_name_plural': 'Ordens de serviço',
                'ordering': ('-criacao', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('tipo', models.CharField(choices=[('servico', 'Serviço / mão de obra'), ('peca', 'Peça / material'), ('deslocamento', 'Deslocamento'), ('outro', 'Outro')], default='servico', max_length=14)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sistema_interno.ordemservico')),
            ],
            options={
                'verbose_name': 'Item da ordem de serviço',
                'verbose_name_plural': 'Itens da ordem de serviço',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EnvioOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('canal', models.CharField(choices=[('link', 'Link copiado'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail')], db_index=True, max_length=10)),
                ('destino', models.CharField(blank=True, max_length=254)),
                ('sucesso', models.BooleanField(default=True)),
                ('detalhe', models.CharField(blank=True, max_length=240)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_ordem_servico', to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='sistema_interno.ordemservico')),
            ],
            options={
                'verbose_name': 'Envio de ordem de serviço',
                'verbose_name_plural': 'Envios de ordens de serviço',
                'ordering': ('-criacao', '-id'),
            },
        ),
    ]
