# Generated by Django 5.2.8 on 2026-08-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_interno', '0027_migrar_orcamentos_enviados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_resposta', 'Aguardando ciência'), ('aberta', 'Aberta'), ('agendada', 'Agendada'), ('em_execucao', 'Em execução'), ('aguardando_peca', 'Aguardando peça'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], db_index=True, default='rascunho', max_length=20),
        ),
    ]
