# Generated by Django 5.2.8 on 2026-08-30 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_alter_manutencao_status'),
        ('sistema_interno', '0029_aceite_validacoes_e_observador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaDivulgacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('promocao', 'Promoção'), ('combo', 'Combo'), ('cupom', 'Cupom')], db_index=True, max_length=12)),
                ('status', models.CharField(choices=[('fila', 'Na fila'), ('andamento', 'Em andamento'), ('concluida', 'Concluída'), ('parcial', 'Concluída com falhas'), ('falha', 'Falhou'), ('cancelada', 'Cancelada')], db_index=True, default='fila', max_length=12)),
                ('segmento', models.CharField(choices=[('todos', 'Todos os clientes ativos'), ('residencial', 'Clientes residenciais'), ('comercial', 'Empresas e comércios'), ('buffet', 'Buffets parceiros'), ('condominio', 'Condomínios'), ('escola', 'Escolas'), ('orgao', 'Órgãos públicos')], default='todos', max_length=14)),
                ('titulo', models.CharField(max_length=140)),
                ('mensagem', models.TextField(max_length=1200)),
                ('imagem_url', models.URLField(blank=True, max_length=700)),
                ('destino_url', models.URLField(blank=True, max_length=700)),
                ('codigo_cupom', models.CharField(blank=True, max_length=20)),
                ('canal_email', models.BooleanField(default=False)),
                ('canal_whatsapp', models.BooleanField(default=False)),
                ('total_destinatarios', models.PositiveIntegerField(default=0)),
                ('total_enviados', models.PositiveIntegerField(default=0)),
                ('total_falhas', models.PositiveIntegerField(default=0)),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_divulgacao', to='core.combos')),
                ('cupom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_divulgacao', to='core.cupom')),
                ('promocao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_divulgacao', to='core.promocoes')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_divulgacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campanha de divulgação',
                'verbose_name_plural': 'Campanhas de divulgação',
                'ordering': ('-criacao', '-id'),
            },
        ),
        migrations.CreateModel(
            name='EntregaCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], db_index=True, max_length=10)),
                ('nome_destinatario', models.CharField(max_length=120)),
                ('destino', models.CharField(max_length=254)),
                ('destino_chave', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('aguardando', 'Aguardando envio no WhatsApp'), ('enviado', 'Enviado'), ('falhou', 'Falhou'), ('ignorado', 'Ignorado')], db_index=True, default='pendente', max_length=12)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('proxima_tentativa_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('processando_desde', models.DateTimeField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.CharField(blank=True, max_length=300)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='sistema_interno.campanhadivulgacao')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_campanha', to='sistema_interno.cliente')),
            ],
            options={
                'verbose_name': 'Entrega de campanha',
                'verbose_name_plural': 'Entregas de campanhas',
                'ordering': ('canal', 'nome_destinatario', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='campanhadivulgacao',
            index=models.Index(fields=['status', 'criacao'], name='campanha_status_data_idx'),
        ),
        migrations.AddIndex(
            model_name='entregacampanha',
            index=models.Index(fields=['canal', 'status', 'proxima_tentativa_em'], name='entrega_fila_canal_idx'),
        ),
        migrations.AddConstraint(
            model_name='entregacampanha',
            constraint=models.UniqueConstraint(fields=('campanha', 'canal', 'destino_chave'), name='campanha_canal_destino_unico'),
        ),
    ]
