# Generated by Django 5.2.8 on 2026-08-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema_interno", "0032_preencher_documento_e_canal_do_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="validade",
            field=models.DateField(
                blank=True,
                help_text="Proposta nova nasce com 5 dias. Data anterior a hoje não é aceita: seria enviar ao cliente um documento já vencido.",
                null=True,
                verbose_name="Válido até",
            ),
        ),
    ]
