# Generated by Django 5.2.8 on 2026-08-31 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema_interno", "0033_alter_orcamento_validade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExclusaoRegistrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quando", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("autor_nome", models.CharField(max_length=150)),
                (
                    "tipo",
                    models.CharField(
                        db_index=True,
                        help_text="Modelo do objeto apagado, em linguagem de gente: Orçamento, O.S.…",
                        max_length=60,
                    ),
                ),
                (
                    "identificacao",
                    models.CharField(
                        help_text="Como o objeto era chamado na tela: '#412 — Buffet Alegria'.",
                        max_length=200,
                    ),
                ),
                (
                    "resumo",
                    models.TextField(
                        blank=True,
                        help_text="O que ele continha, para o caso de alguém precisar reconstituir.",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        help_text="O que a pessoa escreveu ao confirmar.",
                        max_length=240,
                    ),
                ),
                ("forcada", models.BooleanField(db_index=True, default=False)),
                (
                    "autor",
                    models.ForeignKey(
                        help_text="Fica nulo se a conta for removida depois; o nome abaixo permanece.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exclusoes_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exclusão registrada",
                "verbose_name_plural": "Exclusões registradas",
                "ordering": ("-quando", "-id"),
            },
        ),
    ]
