# Generated by Django 5.2.8 on 2026-08-31 19:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema_interno", "0034_exclusaoregistrada"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="desconto",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="frete",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Deslocamento / frete",
            ),
        ),
    ]
