# Generated by Django 5.2.8 on 2026-09-01 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0111_pecasreposicao_uso"),
        ("sistema_interno", "0035_ordemservico_frete_desconto"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemordemservico",
            name="peca",
            field=models.ForeignKey(
                blank=True,
                help_text="Peça da loja ou item de manutenção que originou a linha.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens_ordem_servico",
                to="core.pecasreposicao",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="motivo_refacao",
            field=models.TextField(
                blank=True,
                help_text="O que mudou em relação à versão anterior desta O.S.",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="ordem_anterior",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordem_refeita",
                to="sistema_interno.ordemservico",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="versao",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="status",
            field=models.CharField(
                choices=[
                    ("rascunho", "Rascunho"),
                    ("aguardando_resposta", "Aguardando ciência"),
                    ("aberta", "Aberta"),
                    ("agendada", "Agendada"),
                    ("em_execucao", "Em execução"),
                    ("aguardando_peca", "Aguardando peça"),
                    ("concluida", "Concluída"),
                    ("cancelada", "Cancelada"),
                    ("substituida", "Substituída por nova versão"),
                ],
                db_index=True,
                default="rascunho",
                max_length=20,
            ),
        ),
    ]
