# Generated by Django 5.2.8 on 2026-09-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_interno', '0039_item_os_quantidade_inteira_esquema'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnpj_estabelecimento',
            field=models.CharField(blank=True, db_index=True, max_length=14, verbose_name='CNPJ do estabelecimento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_estabelecimento',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do estabelecimento do cliente'),
        ),
    ]
