# Generated by Django 5.2.8 on 2026-09-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_pecasreposicao_uso'),
        ('sistema_interno', '0040_estabelecimento_do_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIdentidade',
            fields=[
                ('email', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('titular', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('cnpj_estabelecimento', ''), _negated=True), fields=('cnpj_estabelecimento',), name='cliente_cnpj_negocio_unico'),
        ),
    ]
