# Generated by Django 5.2.8 on 2026-09-02 19:08

import django.db.models.functions.text
from django.db import migrations, models


def conferir(apps, schema_editor):
    Endereco = apps.get_model("sistema_interno", "EnderecoCliente")
    vistos = set()
    for row in Endereco.objects.using(schema_editor.connection.alias).values_list(
            "cliente_id", "endereco", "numero", "complemento", "cidade", "estado", "pais"):
        if row[0] is None:
            continue
        chave = (row[0], *[(v or "").strip().lower() for v in row[1:]])
        if chave in vistos:
            raise RuntimeError("Endereço duplicado no mesmo cliente. Execute auditar_identidades e corrija antes de migrate. Nada foi apagado.")
        vistos.add(chave)


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_interno', '0042_email_global'),
    ]

    operations = [
        migrations.RunPython(conferir, migrations.RunPython.noop),
    ]
