# Generated by Django 5.2.8 on 2026-09-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_interno', '0048_avisos_do_aplicativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaMaterial',
            fields=[
                ('prefixo', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('ultimo', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='foto',
            field=models.ImageField(blank=True, upload_to='materiais/fotos/'),
        ),
        migrations.AddField(
            model_name='material',
            name='foto_miniatura',
            field=models.ImageField(blank=True, editable=False, upload_to='materiais/miniaturas/'),
        ),
        migrations.AddField(
            model_name='tipomaterial',
            name='prefixo',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='codigo_interno',
            field=models.CharField(blank=True, help_text='Gerado automaticamente por tipo. Códigos anteriores são preservados.', max_length=30, verbose_name='Código interno'),
        ),
    ]
