# Generated by Django 5.2.8 on 2026-09-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_interno', '0050_preencher_codigos_materiais'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquematerial',
            name='custo_estimado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='estoquematerial',
            name='saldo_valor',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='custo_estimado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='data_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_registradas', to='sistema_interno.fornecedor'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='fornecedor_nome',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='saldo_valor_resultante',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='variacao_valor',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='estoquematerial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoque', to='sistema_interno.material'),
        ),
        migrations.AlterField(
            model_name='estoquematerial',
            name='preco_fornecedor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo médio por unidade'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='sistema_interno.estoquematerial'),
        ),
        migrations.CreateModel(
            name='HistoricoCodigoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('anterior', models.CharField(blank=True, max_length=30)),
                ('novo', models.CharField(max_length=30)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_codigos', to='sistema_interno.material')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
