# Generated by Django 5.2.8 on 2026-09-04 13:11

import django.db.models.deletion
import django.utils.timezone
import sistema_interno.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema_interno", "0052_saldos_iniciais_custos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # A troca do `id` de EmailIdentidade que o makemigrations quis fazer
    # junto NÃO entra aqui. Ela recria a tabela, e a tabela tem gatilhos
    # apontando para ela (ver `_email_escopo.py`): a recriação derruba o
    # gatilho no meio do caminho e quebra qualquer INSERT em auth_user.
    # É uma pendência anterior a esta mudança e continua sendo dela.
    operations = [
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("atualizado", models.DateTimeField(auto_now=True, null=True)),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("orcamento", "Orçamento"),
                            ("ordem_servico", "Ordem de serviço"),
                            ("loja", "Pedido da loja"),
                        ],
                        db_index=True,
                        default="orcamento",
                        max_length=16,
                    ),
                ),
                ("nome_cliente", models.CharField(blank=True, max_length=120)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Valor desta venda",
                    ),
                ),
                (
                    "valor_documento",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("forma_pagamento", models.CharField(blank=True, max_length=120)),
                ("observacao", models.CharField(blank=True, max_length=240)),
                (
                    "recebida_em",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("registrada", "Registrada"),
                            ("documento", "Documento emitido"),
                            ("assinada", "Assinada pelo cliente"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="registrada",
                        max_length=12,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=sistema_interno.models.gerar_token_venda,
                        editable=False,
                        help_text="Chave do documento que o cliente abre e assina.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("documento_emitido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendas",
                        to="sistema_interno.cliente",
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendas",
                        to="sistema_interno.orcamento",
                    ),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendas",
                        to="sistema_interno.ordemservico",
                    ),
                ),
                (
                    "registrada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendas_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
                "ordering": ("-recebida_em", "-id"),
            },
        ),
        migrations.CreateModel(
            name="AceiteVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_publico",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("assinante_nome", models.CharField(max_length=120)),
                ("assinante_documento", models.CharField(max_length=14)),
                ("consentimento", models.BooleanField(default=True)),
                ("venda_hash", models.CharField(max_length=64)),
                ("ip_hash", models.CharField(max_length=64)),
                ("navegador_hash", models.CharField(max_length=64)),
                ("termos_versao", models.CharField(default="2026-08", max_length=20)),
                ("assinado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "venda",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aceite_eletronico",
                        to="sistema_interno.venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura de venda",
                "verbose_name_plural": "Assinaturas de vendas",
                "ordering": ("-assinado_em",),
            },
        ),
        migrations.AddIndex(
            model_name="venda",
            index=models.Index(
                fields=["origem", "recebida_em"], name="venda_origem_data_idx"
            ),
        ),
    ]
